dist: bionic
language: python
cache: pip
env:
  global:
    - USERNAME=obscuritylabs
    - IMAGE=pefixup

before_install:
  - sudo apt-get install build-essential libffi-dev libfuzzy-dev ssdeep

install:
  - pip install -r requirements.txt

script:
  - ls
 # - pytest

matrix:
  include:
    - python: '3.7'
    - python: '3.6'

  - stage: release
    install: skip
    script: skip
    before_deploy:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    deploy:
      # deploy development to docker hub
      - provider: script
        script: 
          - bash ./scripts/release_docker.sh
        on:
          branch: development

      # deploy master to docker hub
      - provider: script
        script: 
          - bash ./scripts/release_docker.sh
        on:
          branch: master