dist: bionic
language: python
cache: pip
python:
#  - "3.4"
#  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
env:
  - USERNAME=obscuritylabs
  - IMAGE=pefixup
  
before_install:
  - sudo apt-get install build-essential libffi-dev libfuzzy-dev ssdeep

install:
  - pip install -r requirements.txt

before_script:
  - ./script/build_docker.sh

script:
  - pytest