dist: bionic
language: python
cache: pip
env:
  global:
  - USERNAME=obscuritylabs
  - IMAGE=pefixup
  # DOCKER USER
  - secure: "dxdD636pSjeabVoOxiJaXlc47BdOK0oQutGTcXTSlSkcOf3XlDvwBP3aOSGGc4VtL5RtZsl6Ftul2/id+rozlbRMeI9fKN7cXcfVE9V1P6Dn1fLx+Oue8FOsAUBj1KlcO0bkctCdwuH4ZJws1DcC/5pbSZvWh5hshrm8ViQlh4BJcchZJXm7AnnxvrdYTRbP9nXf9oIShP4n1D5jEdmHbn0Mx68AkeSaCgsou6NtEcVEJ1D4mHwR1s61twwCBhx/qdr/TfCVEsuhTLPukK79oyaYpaMe9iA0jpM5p+9EDApt9TOwjK6v3RYDsUmdgJ4c4fmnyntk3mrhndeANoP/sgyY3CbaEnyjSwXQCAwzDu+S486/pyGeZwGKn37OxvAPhLI2gtEGrs6yR1vjFnr66HCzNOoZRqnm9nFwFs5fCZqhGEfXgFPYYVXlb1M6w6II1bdcLXhoo34KPV/fBI5u5UAeT/LzsEPUdgZS1NGw4YTrN6lN+uCzhNMgrnNWnGu+7jJVWDNxFmu2ME2N3XrxGrp35n4hm17lC+XIL2sAZq6+oCs8IwKCrzuuvY4SdIsjFmOAlSToAfnGoCujIMdc1N9qZ7cifWTpQzVHuLvuSF4HQm9WUrKjiGoMoADDKVsU4G4nGPTQUDU2i2siROux5WI37HgFBx2C4LGPgLmAip4="
  # DOCKER PASS
  - secure: "lK3viCUg2RIJJvahx0F1xfCA68uHjSqXfFyuElx4hwm6pqiMK0bDlkusiduehucn1PKrNRddNiAzkdcIjL5ma9B93K1x/0y8nxZGiKFlUo77qibgIps+LV2CWEvtbwaqT0PP8iqEBBiiTdjtJ0xo1JkiS33qEHTOYXKn9zyMtW9oK0FG5xgM+qavtl/T0DPvdU59lx6qRWkSGa8NPS7fyPAt+HM96DiFyXZKFL1oTlBItI9nEVqktlhEkDAfKyccgMIW/Dr7gF9OM9gcAN1Pqv8Ylbi8Nhz0Bqcqv+aV0obch4UIkgekCPGwykhiYPfje3SI84jdPSztOaX5JzC4e76ugAoLwlUX20mRekTb8DHrNb6IdqmDPXbAF9HHLeN7BRd+LhBEuWMYFWxd045QTIwiAxznrjMFIATUyPE22nzA+6icuNs5U5CdTb/EPaipBzhTeETONvfFE6X/G7wBfoyrsVJ2uu2dVSyKFWmqsU8Ilfsf0pKuPTxz+o5FtZrCkWh8L/OAkEhGjL98BbFCb4Wl1fazgKuGyQF40Z2us+yy0xyEECrLId/FmQZ9+ACURKmHto4lzCzo+as/psApBMNzcEaoLR7IDUYLucwthLBXOM116SIvYqtg9L2PfMkbVoKQHq7U6TuHMKPsSj9P74ItAl89LHEg9UBRy59XDBs="
python:
  - '3.6'
  - '3.7'
  - '3.7-dev'
  - '3.8-dev'
  - 'nightly'

before_install:
  - sudo apt-get install build-essential libffi-dev libfuzzy-dev ssdeep

install:
  - pip install -r requirements.txt

script:
  - ls
 # - pytest

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

deploy:
  # deploy development to docker hub
  - provider: script
    script: 
      - bash ./scripts/release_docker.sh
    on:
      branch: development

  # deploy master to docker hub
  - provider: script
    script: 
      - bash ./scripts/release_docker.sh
    on:
      branch: master
